### PR TITLE
enable passing a userMediaStream as an option

### PR DESCRIPTION
**Pull request by mreinstein**
related to #26

### CODE REVIEW

**Comment by nfriedly** [comment]
I like this. Two thoughts: 

1) can you rename the param to just `options.mediaStream`

2) Have you tested this for your use case in in various browsers? I seem to remember some trouble in the past with attempting to use a MediaStream in multiple AudioContexts. That may have just been browser bugs that have since been ironed out, I'd feel better if you at least confirmed that this works for your needs. ([npm link](https://docs.npmjs.com/cli/link) is handy for testing these kinds of things ahead of time)

**Comment by mreinstein** [comment]
> can you rename the param to just options.mediaStream

sounds good.

> Have you tested this for your use case in in various browsers?

I have done considerable testing in chrome, and light testing in firefox and Chrome for Android. Haven't touched edge yet. Happy to help with this though.

> I seem to remember some trouble in the past with attempting to use a MediaStream in multiple AudioContexts

Oh, interesting! It's unclear to me what an AudioContext exactly *is* vs a mediaStream. I'm wondering if it makes more sense to pass in an audio context instead of a medisaStream? 

Any info you could share on this would be helpful.

**Comment by nfriedly** [comment]
So, the idea with an Audio Context is that it's sort of a bucket for a bunch of audio nodes - inputs (like the microphone MediaStreamor a sine wave), outputs (speakers, or a network connection for WebRTC), and processing nodes that can adjust volume, mix inputs, add distortion, etc.

I believe it exists mainly to enable under-the-hood optimizations so that you can do various transformations in real-time without taking up too much processing power.

The MicrophoneStream library creates a context, adds the MediaStream, and then adds a script processing node that just extracts the audio and sends it out as a node.js stream. 

I have hazy memories of trying to preserve just the MediaStream for the keepMic option, but getting errors the second time around because even though I had removed the MediaStream from the original Audio Context and then closed that context, the browsers still refused to let me add the MediaStream to a new Audio Context. (The initial implementations of WebAudio were pretty buggy, especially in chrome.) But, if that's no longer an issue, then I'll be happy and probably able to clean up the keepMic code a bit.

Here's the AudioContext code: https://github.com/saebekassebil/microphone-stream/blob/master/microphone-stream.js (It's saebekassebil's module, but I'm mostly responsible for it these days.)

And, here's some docs on it https://developer.mozilla.org/en-US/docs/Web/API/AudioContext

**Comment by nfriedly** [comment]
Should be released in v0.31.0 shortly.

**Comment by mreinstein** [comment]
awesome! Thanks for the information, that's definitely helpful. :)

I'm going to play around with several permutations of the `keepMic` and `userMedia` options, along with some cross browser tests. 

I also have some questions around the `L16` stream stuff, and some of the code, which I'll post in a separate issue/question thread.

**Comment by germanattanasio** [comment]
Great work @mreinstein!

**Pull request merged**
