### PR TITLE
feat: update parameter names in recognize/synthesize streams to be lower camel case

### PR DESCRIPTION
**Pull request by dpopp07**
* this is to match the recent changes in the watson node sdk
* `access_token` is renamed to `accessToken` in all modules

This certainly presents breaking changes but I don't know that the library is ready for 1.0 so I suppose we're taking advantage of the fact that we're in pre-release.

### CODE REVIEW

**Comment by germanattanasio** [comment]
@dpopp07 the changes look good. Did you run all the examples in the example folder? you can run them locally and then check each one of them to make sure they work

**Comment by dpopp07** [comment]
@germanattanasio No I have not - good call. I'll update those today.

**Comment by dpopp07** [comment]
While updating the examples, I discovered a few mistakes I had made. I pushed the updated code. The examples are all working now.

**Comment by germanattanasio** [comment]
I think the changes look good. One last request, can you update the CHANGELOG describing the changes to `camelCase`: https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/CHANGELOG.md

**Comment by dpopp07** [comment]
Yes, good call

**Comment by dpopp07** [comment]
Changelog updated

**Pull request merged**
