### PR TITLE
fix: 降采样后的文件有噪声

### PR DESCRIPTION
**Pull request by mingzhi22**
##### Checklist

- [x] `npm test` passes (tip: `npm run autofix` can correct most style issues)
- [ ] tests are included
- [ ] readme and/or JSDoc is updated

### CODE REVIEW

**Comment by germanattanasio** [comment]
@mingzhi22 why?

**Comment by mingzhi22** [comment]
> @mingzhi22 why?

```
   var indexSampleAfterLastUsed = Math.round(samplingRateRatio * i); // 'i' is out of range
   var remaining = buffer.length - indexSampleAfterLastUsed;
   if (remaining > 0) { // 'remaining' is always less than 0
```

**Comment by germanattanasio** [comment]
I'll let @dpopp07 decide

**Comment by mingzhi22** [comment]
**`for (i = 0; i < outputBuffer.length; i++) {`**

img_0660

**Comment by mingzhi22** [comment]
// `i` will be out of range, `remaining` will always be less than 0
**`for (i = 0; i + filter.length - 1 < buffer.length; i++) {`** 

img_4071

**Comment by daniel-bolanos** [comment]
I'm not sure this change is correct. The first loop needs to iterate over the elements in the output buffer, since it is producing the output samples from the input samples. Also, are you sure `i` will be out of range?

**Comment by mingzhi22** [comment]
hi @dpopp07 @daniel-bolanos, here is my user-case. Download and run `npm install && npm run build && npm start` to start.

[downsample.zip](https://github.com/watson-developer-cloud/speech-javascript-sdk/files/2422910/downsample.zip)

**Comment by germanattanasio** [comment]
@mingzhi22 sorry for the delay I didn't see your comment before.


@dpopp07 can you check if running the audio from @mingzhi22 you run in the `out of bound` exception?

**Comment by tomoyamachi** [comment]
@mingzhi22 
I used `webaudio-l16-stream` to creating a WAVE file, but the file has some noises.
It becomes very clear sound when applied your PR patch.

Thanks!

**Pull request merged**
